# .streamlit/secrets.toml

[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1AMPLYNU6w7znGrkNf3pb3HLhhbvgMJFUt6AJcgozs0Q/edit?gid=0#gid=0"

type =  "service_account"
project_id = "valiant-lambda-433822-j6"
private_key_id = "73a7bbe50353c378e302012db3b3ed9449faf8c0"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC7uR7XcvMjpG3L\neCu60jTepVaEK8CdKazYvsFaQuJymi2CcKPh9QyMREFKdfkgOjBVRZBJZtm8mEsj\ns1Z9kBv+4M4xAB+A+Mn84omNcGvrQhxzseh1ZkzJpruaqNMMHY0lbTxdIJ3BNyAm\n+i633PJU/9FCHE5/ZGOf5XuniIpwJufBYanUxF4eOcWkPhn8Z3di9MKkzYlgkHpr\nZGkdFdrxKC6etZJiHLGrtRgOMSUVUVE4AY4700TAfzjgDgJL8iFceGGB3A0z58YR\naGp4hw4rRJ3YQRTipyAOVAqKznt2Cy2Pm2pcpW3Va051vlKJgnkrl+TjhZycWfY+\nLMZ8hlVDAgMBAAECggEAEarilDRlXb1j9/pfYz3Va/7znYzgm+oIMn4BhJU26sJH\n9jbTtbhybeEeo/tmbvoLAnuBkOb1JyLOL5X5VefyOpK91S7FyEWh/QL1HzKtdX7L\nXrgnwKTYJUJj9bJd6o39csBNJhajwkOF6yUwsG1DAWzyLN6tJKA2IB5g/OuE2/kj\nwuM0f01F+1o9AqKBXqGG6gd7YBwpdPuqzSt5NS8X2h9Deabo+OKczwpX6BR5u4vj\nPhZVhaVyLiO28lLXQzI0poq0EQfZF5t5RRW/M71DDezPMnpazPLOTjpWG2eE1nkW\n+EXDjFscpoew0ObcgB9Mmv3oHicWqDuJs0ilMYuNwQKBgQD63iN/wk+D7DS4JxWU\nK96CNM0QYJkxhDdqe2EmQO1C+gb594+uu9O5WGZpk95c31BdBaTAiQcG5uP8WcoH\n6+V72tDiEAAM+NKu25YCHzLbREzTTojXf4b48d7P8MPU0to8CdaT8gmO8rpQUJWW\nvaZT8tHKf71uzkjfHwwP7KiRLQKBgQC/kEbSpHqcFCCYvezsCNxmltAlf/19/1TB\nNc/c5cZvEw62G+0Ai5LHHY166V+oAKUHtHSPcUNzKLfpmMkPCvy3Esft253SbrDH\nf5MkjUX4qeEABoA9FYdH8Jo8sA32E9ZnVsFbzpt/MN8sRgtKSDdCWIuJHxVYAHH2\n9oWh4oMmLwKBgQCiGWWgyQKuQLN0BrU3z/zv74RNv81dJIzWPjDxEeT9cSeO33s1\nMeLGEavjLovxQM7hvKLPUft7ZzgLuE0GP1RCaoqseCBAQYuJNxQ//L7U1dY6d7WO\nYbXqKAeMH4u6eiBPyR+g6zVn68md2eQ+yf6uoekTSuUxsxN9MMePhqEJZQKBgQCp\nD/zhRFYNT1ohU2U4Pu29AJa8scOXonM7fXFww70oJEqUf/rfw06LulI1yqcoT0FW\nlnVUbyKXDLWbTMMNKqY0MDgQfQVBRX1w4++Jj8DUH6E6c4JT5p8Y54hHzRzVM1bC\npvdJPgNP8mLT4RFvwmI6hIjJQIyGuQXbbmArqgwS8wKBgEuXCWxLbF3qIMD7Zhdt\ng/qe0c+c7hM3qX5BJOHYl6nrpVXaiBxCZKhb4kXOl9x0bgCeTnFvcFvW721qm3Yq\nJqql4GnHRukm/9sGQkRlTSxVpZsxeT0MRvByz4LjhqViNYKSvKyn4Z3z6TQkQugP\nuv+trRkpkaCcIamKBDuS41Uk\n-----END PRIVATE KEY-----\n"
client_email = "sheet-ecmo@valiant-lambda-433822-j6.iam.gserviceaccount.com"
client_id = "103764525455650082661"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/sheet-ecmo%40valiant-lambda-433822-j6.iam.gserviceaccount.com"
universe_domain = "googleapis.com"




